# vim: set expandtab ts=2 sw=2:
---
- name: Provision quagga stuff
  hosts: overcloud
  become: yes

  tasks:
    - name: Remove IP from base_interface
      shell: /usr/sbin/ip addr del {{ local_ipaddr }}/{{ del_prefix }} dev {{ base_interface }}
      when: ansible_{{ ansible_interface }}.ipv4 is defined

    - name: Check if dhcp enabled on base_interface
      shell: grep -c "dhcp" /etc/sysconfig/network-scripts/ifcfg-{{ base_interface }}
      register: dhcp_check
      when: ansible_{{ ansible_interface }}.ipv4 is defined

    - name: Switch out dhcp for none on bootproto on base_inteface
      shell: "sed -i s/BOOTPROTO=.*/BOOTPROTO=none/g /etc/sysconfig/network-scripts/ifcfg-{{ base_interface }}"
      when: dhcp_check != "0"

    - name: Configure loopback
      template:
        src: templates/ifcfg-lo.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-lo
      notify:
        - restart loopback

    - name: Configure eth2
      template:
        src: templates/ifcfg-eth2.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth2
      notify:
        - restart eth2

    - name: Configure eth3
      template:
        src: templates/ifcfg-eth3.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth3
      notify:
        - restart eth3

    - name: Copy over Quagga RPMs
      copy:
        src: files/{{ item }}
        dest: /tmp/{{ item }}
      with_items:
        - quagga-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-debuginfo-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-contrib-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-devel-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm

    - name: Install Quagga RPMs
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - /tmp/quagga-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - /tmp/quagga-debuginfo-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - /tmp/quagga-contrib-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - /tmp/quagga-devel-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm

    - name: Set zebra service enabled
      service: name=zebra enabled=yes

    - name: Set bgp service enabled
      service: name=bgpd enabled=yes

    - name: Install Zebra template
      template:
        src: templates/zebra.conf.j2
        dest: /etc/quagga/zebra.conf
        owner: quagga
        group: quaggavt
        mode: 0644
      notify:
        - restart zebra service

    - name: Install BGPd template
      template:
        src: templates/bgpd.conf.j2
        dest: /etc/quagga/bgpd.conf
        owner: quagga
        group: quaggavt
        mode: 0644
      notify:
        - restart bgpd service

    - name: Install vtysh template
      template:
        src: templates/vtysh.conf.j2
        dest: /etc/quagga/vtysh.conf
        owner: quagga
        group: quaggavt
        mode: 0644
      notify:
        - restart zebra service

  handlers:
    - name: restart zebra service
      service: name=zebra state=restarted

    - name: restart bgpd service
      service: name=bgpd state=restarted

    - name: restart loopback
      shell: /usr/sbin/ifdown lo && /usr/sbin/ifup lo

    - name: restart eth2
      shell: /usr/sbin/ifdown eth2 && /usr/sbin/ifup eth2

    - name: restart eth3
      shell: /usr/sbin/ifdown eth3 && /usr/sbin/ifup eth3


