---
- name: Provision quagga stuff
  hosts: overcloud
  become: yes

  tasks:
    - name: Check if eth0 still exists
      stat: path=/etc/sysconfig/network-scripts/ifcfg-eth0
      register: eth0

    - name: Remove IP from eth0
      shell: /usr/sbin/ip addr del {{ local_ipaddr }}/{{ local_prefix }} dev eth0
      when: ansible_eth0.ipv4 is defined and base_interface == "eth0"

    - name: Drop usage of eth0 interface
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        state: absent
      when: eth0.stat.exists and base_interface == "eth0"

    - name: Configure loopback
      template:
        src: templates/ifcfg-lo.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-lo
      notify:
        - restart loopback

    - name: Configure eth2
      template:
        src: templates/ifcfg-eth2.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth2
      notify:
        - restart eth2

    - name: Configure eth3
      template:
        src: templates/ifcfg-eth3.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth3
      notify:
        - restart eth3

    - name: Copy over Quagga RPMs
      copy:
        src: files/{{ item }}
        dest: /tmp/{{ item }}
      with_items:
        - quagga-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-debuginfo-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-contrib-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-devel-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm

    - name: Install Quagga RPMs
      yum:
        name: /tmp/{{ item }}
        state: present
      with_items:
        - quagga-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-debuginfo-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-contrib-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
        - quagga-devel-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm

    - name: Set zebra service enabled
      service: name=zebra enabled=yes

    - name: Set bgp service enabled
      service: name=bgpd enabled=yes

    - name: Install Quagga template
      template:
        src: templates/zebra.conf.j2
        dest: /etc/quagga/zebra.conf
        owner: quagga
        group: quaggavt
        mode: 0644
      notify:
        - restart zebra service

    - name: Install BGPd template
      template:
        src: templates/bgpd.conf.j2
        dest: /etc/quagga/bgpd.conf
        owner: quagga
        group: quaggavt
        mode: 0644
      notify:
        - restart bgpd service

  handlers:
    - name: restart zebra service
      service: name=zebra state=restarted

    - name: restart bgpd service
      service: name=bgpd state=restarted

    - name: restart loopback
      shell: /usr/sbin/ifdown lo && /usr/sbin/ifup lo

    - name: restart eth2
      shell: /usr/sbin/ifdown eth2 && /usr/sbin/ifup eth2

    - name: restart eth3
      shell: /usr/sbin/ifdown eth3 && /usr/sbin/ifup eth3


