# vim: set expandtab ts=2 sw=2:
---
- name: Provision quagga stuff
  hosts: overcloud
  become: yes
  serial: 10
  vars:
    bgp_interfaces:
      - p1p1
      - p1p2
    quagga_rpms:
      - /tmp/quagga-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
      - /tmp/quagga-debuginfo-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
      - /tmp/quagga-contrib-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm
      - /tmp/quagga-devel-0.99.23.1-cl2.5+2.el7.centos.x86_64.rpm

  tasks:
  - name: Remove IP from base_interface
    shell: /usr/sbin/ip addr del {{ local_ipaddr }}/{{ del_prefix }} dev {{ base_interface }}
    when: ansible_{{ ansible_interface }}.ipv4 is defined

  - name: Check if dhcp enabled on base_interface
    shell: grep -c "dhcp" /etc/sysconfig/network-scripts/ifcfg-{{ base_interface }}
    ignore_errors: True
    always_run: True
    changed_when: True
    register: dhcp_check
    when: ansible_{{ ansible_interface }}.ipv4 is defined

  - name: Switch out dhcp for none on bootproto on base_interface
    shell: "sed -i s/BOOTPROTO=.*/BOOTPROTO=none/g /etc/sysconfig/network-scripts/ifcfg-{{ base_interface }}"
    when: dhcp_check.changed == True

  - name: Configure loopback
    template:
      src: templates/ifcfg-lo.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-lo
    notify:
      - restart loopback

  - name: Configure BGP interfaces
    template:
      src: templates/ifcfg-int.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
    register: bgp_items
    always_run: True
    with_items: "{{ bgp_interfaces }}"
    notify:
      - restart bgp network

  - name: Copy over Quagga RPMs
    copy:
      src: files/{{ item }}
      dest: "{{ item }}"
    with_items: "{{ quagga_rpms }}"

  - name: Install Quagga RPMs
    yum: 
      name: "{{ item }}"
      state: present
    with_items: "{{ quagga_rpms }}"

  - name: Set zebra service enabled
    service: name=zebra enabled=yes

  - name: Set bgp service enabled
    service: name=bgpd enabled=yes

  - name: Install Zebra template
    template:
      src: templates/zebra.conf.j2
      dest: /etc/quagga/zebra.conf
      owner: quagga
      group: quaggavt
      mode: 0644
    notify:
      - restart zebra service
      - restart bgpd service
      - pcs resource cleanup

  - name: Install BGPd template
    template:
      src: templates/bgpd.conf.j2
      dest: /etc/quagga/bgpd.conf
      owner: quagga
      group: quaggavt
      mode: 0644
    notify:
      - restart zebra service
      - restart bgpd service
      - pcs resource cleanup

  - name: Install vtysh template
    template:
      src: templates/vtysh.conf.j2
      dest: /etc/quagga/vtysh.conf
      owner: quagga
      group: quaggavt
      mode: 0644
    notify:
      - restart zebra service
      - restart bgpd service
      - pcs resource cleanup

  handlers:
    - name: restart zebra service
      service: name=zebra state=restarted

    - name: restart bgpd service
      service: name=bgpd state=restarted

    - name: restart loopback
      shell: /usr/sbin/ifdown lo && /usr/sbin/ifup lo

    - name: restart bgp network
      shell: /usr/sbin/ifdown {{ item }} && /usr/sbin/ifup {{ item }}
      with_items: "{{ bgp_interfaces }}"

    - name: pcs resource cleanup
      shell: sleep 60 && /sbin/pcs resource cleanup
      when: ansible_nodename == "overcloud-controller-0.localdomain"

- name: Update controller-0 for pacemaker
  hosts: overcloud-controller-0.localdomain
  become: yes

  tasks:
    - name: Update the PCS configuration
      shell: for i in $(pcs resource show | awk  '/IPaddr2/ {print $1}'); do pcs resource update $i nic=lo; done
